const guests = [
  { nombre: "Cecilia y Oscar", numeroInvitados: 2, code: "" },
  { nombre: "Sabina", numeroInvitados: 1, code: "" },
  { nombre: "Marcelo", numeroInvitados: 1, code: "" },
  { nombre: "Graciela y Carlos", numeroInvitados: 2, code: "" },
  { nombre: "Daniela", numeroInvitados: 1, code: "" },
  { nombre: "Eliana, Matias, Joaquin y Ciro", numeroInvitados: 4, code: "" },
  { nombre: "Maricel y Catalina", numeroInvitados: 2, code: "" },
  { nombre: "Constanza y Lucas", numeroInvitados: 2, code: "" },
  { nombre: "Maria", numeroInvitados: 1, code: "" },
  { nombre: "Walter, Marisa, Matias, Alejo y Agustina", numeroInvitados: 5, code: "" },
  { nombre: "Alejandro, Ximena, Sophie y Leon", numeroInvitados: 4, code: "" },
  { nombre: "Mercedes, Alicia y Tomas", numeroInvitados: 3, code: "" },
  { nombre: "Nelida", numeroInvitados: 1, code: "" },
  { nombre: "Analia, Andres y Manuel", numeroInvitados: 3, code: "" },
  { nombre: "Ricardo, Vanina, Julieta, Camila y Federico", numeroInvitados: 5, code: "" },
  { nombre: "Maximiliano", numeroInvitados: 1, code: "" },
  { nombre: "Agustina", numeroInvitados: 1, code: "" },
  { nombre: "Julian y Micaela", numeroInvitados: 2, code: "" },
  { nombre: "Cristina, Romina, Nadia, Santiago y Valentina", numeroInvitados: 5, code: "" },
  { nombre: "Nadia y Pablo", numeroInvitados: 2, code: "" },
  { nombre: "Patricia y Eduardo", numeroInvitados: 2, code: "" },
  { nombre: "Damian", numeroInvitados: 1, code: "" },
  { nombre: "Mariano", numeroInvitados: 1, code: "" },
  { nombre: "Carla", numeroInvitados: 1, code: "" },
  { nombre: "Agustina", numeroInvitados: 1, code: "" },
  { nombre: "Jorge y Laura", numeroInvitados: 2, code: "" },
  { nombre: "Pablo, Analia, Luciana y Agostina", numeroInvitados: 4, code: "" },
  { nombre: "Javier, Andrea, Gianluca y Santino", numeroInvitados: 4, code: "" },
  { nombre: "Orlando, Veronica, Tiziana, Ramiro y Milagros", numeroInvitados: 5, code: "" },
  { nombre: "Anibal y Noemi", numeroInvitados: 2, code: "" },
  { nombre: "Susana", numeroInvitados: 1, code: "" },
  { nombre: "Roberto y Victoria", numeroInvitados: 2, code: "" },
  { nombre: "Nihuel", numeroInvitados: 1, code: "" },
  { nombre: "Mauro", numeroInvitados: 1, code: "" },
  { nombre: "Martin y Francisco", numeroInvitados: 2, code: "" },
  { nombre: "Sofia", numeroInvitados: 1, code: "" },
  { nombre: "Florencia y Santiago", numeroInvitados: 2, code: "" },
  { nombre: "Leandro y Lucia", numeroInvitados: 2, code: "" },
  { nombre: "Ines y Matias", numeroInvitados: 2, code: "" },
  { nombre: "Victoria y Santiago", numeroInvitados: 2, code: "" },
  { nombre: "Belen", numeroInvitados: 1, code: "" },
  { nombre: "Julian", numeroInvitados: 1, code: "" },
  { nombre: "Cristian", numeroInvitados: 1, code: "" },
  { nombre: "Matias", numeroInvitados: 1, code: "" },
  { nombre: "Gonzalo", numeroInvitados: 1, code: "" },
  { nombre: "Nicolas y Milena", numeroInvitados: 2, code: "" },
  { nombre: "Guillermo Y Eugenia", numeroInvitados: 2, code: "" },
  { nombre: "Christian y Daniela", numeroInvitados: 2, code: "" },
  { nombre: "Lisandro, Marie y Valder", numeroInvitados: 3, code: "" }
];